[tasks.python]
command = "maturin"
args = ["build"]
cwd = "python"
dependencies = ["install-maturin"]

[tasks.install-maturin]
command = "pip"
args = ["install", "maturin>=1.0,<2.0"]

[tasks.install-python-sdk.windows]
command = "pip"
args = [
    "install",
    "target/wheels/longbridge-4.0.0-cp311-cp311-win_amd64.whl",
    "-I",
]
dependencies = ["python"]
